### PR TITLE
Update UI search room task.78999

### PR DESCRIPTION
**Pull request by trucquynhCapy**
https://edu-redmine.sun-asterisk.vn/issues/78999
image

### CODE REVIEW

**Comment by hieupham12345** [comment]
That UI look good!

**Comment by Ngansan** [comment]
Delete sidebar.css file because I think it's unused.

**Comment by Ngansan** [comment]
Delete sidebar.css file because I think it's unused.

**Comment by trietpm-0501** [comment]
@trucquynhCapy there are conflicts that must be resolved

**Pull request closed without merging**
